token: '' # Le token du bot discord
guildId: ''
welcomeChannel: 0000
usersFolder: 'users/'
twitchToken: ''
twitchUsername: ''
announceTwitchChannel: 0000
activeAnnounceTwitch: "false"
announceRoleId: 0000